name: ML_Env

channels:
  - conda-forge
  - defaults
  
dependencies:
    - python==3.9
    - numpy==1.20.3
    - scipy==1.6.3
    - pandas==1.2.4
    - scikit-learn==0.24.2
    - joblib==1.0.1
    - jupyter==1.0.0
    - matplotlib==3.4.2
    - plotnine==0.8.0
